import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import katex from "katex";
import type { Root } from "mdast";

const parser = unified().use(remarkParse).use(remarkGfm).use(remarkMath);

/** Standard Markdown syntax with original source positions for concept annotations. */
export function parseMarkdown(text: string): Root {
  return parser.parse(text);
}

/** The only HTML insertion is generated by KaTeX with untrusted commands disabled. */
export function renderFormula(text: string, displayMode: boolean): string {
  return katex.renderToString(text, {
    displayMode, throwOnError: false, trust: false, strict: "ignore",
    maxExpand: 1000, maxSize: 20, output: "htmlAndMathml",
  });
}
